결측치 처리

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(
    [
        [42, "male", 12, "reading", "class2"],
        [35, "unknown", 3, "cooking", "class1"],
        [1000, "female", 7, "cycling", "class3"],
        [1000, "unknown", 21, "unknown", "unknown"],
    ]
)
df.columns = ["age", "gender", "month_birth", "hobby", "target"]

In [3]:
df

age   gender  month_birth    hobby   target
0    42     male           12  reading   class2
1    35  unknown            3  cooking   class1
2  1000   female            7  cycling   class3
3  1000  unknown           21  unknown  unknown

In [4]:
df["age"].unique()

array([  42,   35, 1000])

In [5]:
df["gender"].unique()

array(['male', 'unknown', 'female'], dtype=object)

In [6]:
df["month_birth"].unique()

array([12,  3,  7, 21])

In [7]:
df["hobby"].unique()

array(['reading', 'cooking', 'cycling', 'unknown'], dtype=object)

In [8]:
df["target"].unique()

array(['class2', 'class1', 'class3', 'unknown'], dtype=object)

In [9]:
df.loc[df["age"] > 150, ["age"]] = np.nan
df.loc[df["gender"] == "unknown", ["gender"]] = np.nan
df.loc[df["month_birth"] > 12, ["month_birth"]] = np.nan
df.loc[df["hobby"] == "unknown", ["hobby"]] = np.nan
df.loc[df["target"] == "unknown", ["target"]] = np.nan

In [10]:
df

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading  class2
1  35.0     NaN          3.0  cooking  class1
2   NaN  female          7.0  cycling  class3
3   NaN     NaN          NaN      NaN     NaN

In [11]:
df.isnull().sum()

age            2
gender         2
month_birth    1
hobby          1
target         1
dtype: int64

In [12]:
df2 = df.dropna(axis=0)
df2

age gender  month_birth    hobby  target
0  42.0   male         12.0  reading  class2

In [13]:
df3 = df.dropna(axis=1)
df3

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [14]:
df4 = df.dropna(how="all")
df4

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading  class2
1  35.0     NaN          3.0  cooking  class1
2   NaN  female          7.0  cycling  class3

In [15]:
df5 = df.dropna(thresh=2)
df5

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading  class2
1  35.0     NaN          3.0  cooking  class1
2   NaN  female          7.0  cycling  class3

In [16]:
df6 = df.dropna(subset=["gender"])
df6

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading  class2
2   NaN  female          7.0  cycling  class3

In [17]:
alter_values = {
    "age": 0,
    "gender": "U",
    "month_birth": 0,
    "hobby": "U",
    "target": "class4",
}

In [18]:
df7 = df.fillna(value=alter_values)
df7

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading  class2
1  35.0       U          3.0  cooking  class1
2   0.0  female          7.0  cycling  class3
3   0.0       U          0.0        U  class4

클래스 라벨 설정

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
df8 = df7
class_label = LabelEncoder()
data_value = df8["target"].values
y_new = class_label.fit_transform(data_value)
y_new

array([1, 0, 2, 3])

In [23]:
df8["target"] = y_new
df8

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading       1
1  35.0       U          3.0  cooking       0
2   0.0  female          7.0  cycling       2
3   0.0       U          0.0        U       3

In [24]:
y_ori = class_label.inverse_transform(y_new)
y_ori

array(['class2', 'class1', 'class3', 'class4'], dtype=object)

In [25]:
df8["target"] = y_ori
df8

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading  class2
1  35.0       U          3.0  cooking  class1
2   0.0  female          7.0  cycling  class3
3   0.0       U          0.0        U  class4

In [26]:
y_arr = df8["target"].values
y_arr.sort()
y_arr

array(['class1', 'class2', 'class3', 'class4'], dtype=object)

In [28]:
num_y = 0
dic_y = {}
for ith_y in y_arr:
    dic_y[ith_y] = num_y
    num_y += 1
dic_y

{'class1': 0, 'class2': 1, 'class3': 2, 'class4': 3}

원-핫 인코딩

In [29]:
df9 = df8
df9["target"] = df9["target"].astype(str)
df10 = pd.get_dummies(df9["target"])
df10

class1  class2  class3  class4
0    True   False   False   False
1   False    True   False   False
2   False   False    True   False
3   False   False   False    True

In [30]:
df9["target"] = df9["target"].astype(str)
df11 = pd.get_dummies(df9["target"], drop_first=True)
df11

class2  class3  class4
0   False   False   False
1    True   False   False
2   False    True   False
3   False   False    True

In [32]:
df12 = df8
df13 = pd.get_dummies(df12)
df13

age  month_birth  gender_U  gender_female  gender_male  hobby_U  \
0  42.0         12.0     False          False         True    False   
1  35.0          3.0      True          False        False    False   
2   0.0          7.0     False           True        False    False   
3   0.0          0.0      True          False        False     True   

   hobby_cooking  hobby_cycling  hobby_reading  target_class1  target_class2  \
0          False          False           True           True          False   
1           True          False          False          False           True   
2          False           True          False          False          False   
3          False          False          False          False          False   

   target_class3  target_class4  
0          False          False  
1          False          False  
2           True          False  
3          False           True

In [33]:
from sklearn.preprocessing import OneHotEncoder

In [34]:
hot_encoder = OneHotEncoder()
y = df7[["target"]]
y_hot = hot_encoder.fit_transform(y)
y_hot.toarray()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
from tensorflow.keras.utils import to_categorical

In [38]:
y_hotec = to_categorical(y_new)
y_hotec

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

데이터 스케일링

In [39]:
from sklearn.preprocessing import StandardScaler

In [41]:
# standard scaling
std = StandardScaler()
std.fit(df8[["month_birth"]])
x_std = std.transform(df8[["month_birth"]]) 
x_std

array([[ 1.44444444],
       [-0.55555556],
       [ 0.33333333],
       [-1.22222222]])

In [44]:
np.mean(x_std)

np.float64(-5.551115123125783e-17)

In [46]:
np.std(x_std)

np.float64(1.0)

In [48]:
from sklearn.preprocessing import RobustScaler

In [49]:
# robust scaling: 극단값을 영향 X
robust = RobustScaler()
robust.fit(df8[["month_birth"]])
x_robust = robust.transform(df8[["month_birth"]])
x_robust

array([[ 1.16666667],
       [-0.33333333],
       [ 0.33333333],
       [-0.83333333]])

In [50]:
from sklearn.preprocessing import MinMaxScaler

In [51]:
# min-max scaling
minmax = MinMaxScaler()
minmax.fit(df8[["month_birth"]])
x_minmax = minmax.transform(df8[["month_birth"]])
x_minmax

array([[1.        ],
       [0.25      ],
       [0.58333333],
       [0.        ]])

In [52]:
from sklearn.preprocessing import Normalizer

In [54]:
# normal scaling
normal = Normalizer()
normal.fit(df8[["age", "month_birth"]])
x_normal = normal.transform(df8[["age", "month_birth"]])
x_normal

array([[0.96152395, 0.27472113],
       [0.99634665, 0.08540114],
       [0.        , 1.        ],
       [0.        , 0.        ]])

In [55]:
stand_scale = StandardScaler()
x_train_std = stand_scale.fit_transform(x_train)
x_test_std = stand_scale.transform(x_test) # transform: training에서 사용되었던 평균, 표준 편차 등 테스트 데이터에 동일 사용

NameError: name 'x_train' is not defined