In [1]:
import numpy as np

In [3]:
input_data = np.array([[2, 3], [5, 1]])
x = input_data.reshape(-1)

In [ ]:
w1 = np.array([2, 1, -3, 3])
w2 = np.array([1, -3, 1, 3])
b1 = 3
b2 = 3

In [5]:
W = np.array([w1, w2])
W

array([[ 2,  1, -3,  3],
       [ 1, -3,  1,  3]])

In [ ]:
b = np.array([b1, b2])
b

array([3, 3])

In [ ]:
weight_sum = np.dot(W, x) + b
weight_sum

array([-2,  4])

In [ ]:
res = 1 / (1 + np.exp(-weight_sum))
res

array([0.11920292, 0.98201379])